name: Build

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          architecture: x64
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Set gradle wrapper permissions
        run: chmod +x ./gradlew
      - name: Build project
        run: ./gradlew build
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: dummykeybinds
          path: build/distributions/dummykeybinds*
          if-no-files-found: error
          compression-level: 0 # compression isn't needed